version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    volumes:
      - ./data/minio:/data
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: ${EXCALIDRAW_S3_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${EXCALIDRAW_S3_SECRET_ACCESS_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  excalidraw-json:
    image: ${BUILDREPO}/excalidraw-json:latest
    depends_on:
      - minio
    environment:
      - EXCALIDRAW_S3_ENDPOINT
      - EXCALIDRAW_S3_BUCKET_NAME
      - EXCALIDRAW_S3_ACCESS_KEY_ID
      - EXCALIDRAW_S3_SECRET_ACCESS_KEY
      - EXCALIDRAW_S3_FORCE_PATH_STYLE
      - EXCALIDRAW_ALLOWED_ORIGIN
    expose:
      - "3000"
    restart: on-failure
    healthcheck:
      disable: true

  excalidraw-room:
    image: ${BUILDREPO}/excalidraw-room:latest
    expose:
      - "80"
    restart: on-failure
    healthcheck:
      disable: true

  excalidraw:
    image: ${BUILDREPO}/excalidraw:latest
    depends_on:
      - excalidraw-room
      - excalidraw-json
    expose:
      - "80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_V1_GET_URL
      - REACT_APP_BACKEND_V2_GET_URL
      - REACT_APP_BACKEND_V2_POST_URL
      - REACT_APP_SOCKET_SERVER_URL
    volumes:
      - ./excalidraw/:/opt/node_app/app:delegated
      - ./excalidraw/package.json:/opt/node_app/package.json
      - ./excalidraw/package-lock.json:/opt/node_app/package-lock.json
      - excalidraw-notused:/opt/node_app/app/node_modules

  nginx:
    image: ${BUILDREPO}/nginx:latest
    restart: on-failure 
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - ./data/nginx:/config:Z
    environment:
      - PUB_SRV_NAME
      - ENABLE_LETSENCRYPT
      - ENABLE_HTTP_REDIRECT
      - DISABLE_HTTPS
      - LETSENCRYPT_DOMAIN
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_USE_STAGING
      - NGINX_RESOLVER
      - TZ

volumes:
  excalidraw-notused:

networks:
  default:
    external:
      name: excalidraw-net

